#!/usr/bin/env node
// Bundles src/ into the single self-contained index.html at the repo root.
// That root file is the form the game is actually played from — opened
// directly in a browser, or published whole as a Claude Artifact — so it
// stays a build *output*, checked into git, regenerated by this script
// rather than hand-edited. See README.md's Development section.
//
// Usage: node build.js [--watch]
import * as esbuild from 'esbuild';
import { readFileSync, writeFileSync, watch } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, 'src');
const OUT = join(__dirname, 'index.html');

// Order matters here the same way it mattered inside the old single <style>
// block — later rules can win ties with earlier ones at equal specificity.
const CSS_FILES = ['base.css', 'frame.css', 'minigames.css', 'overlays.css', 'dev-bar.css'];

async function build() {
  const template = readFileSync(join(SRC, 'index.html'), 'utf8');
  const css = CSS_FILES.map((name) => readFileSync(join(SRC, 'styles', name), 'utf8')).join('\n');

  const result = await esbuild.build({
    entryPoints: [join(SRC, 'main.js')],
    bundle: true,
    format: 'iife',
    target: 'es2019',
    write: false,
    logLevel: 'warning'
  });
  const js = result.outputFiles[0].text;

  let html = template;
  // Fold the <link rel="stylesheet"> tags into one inline <style>.
  html = html.replace(/(?:<link rel="stylesheet"[^>]*>\n?)+/, '<style>\n' + css + '\n</style>\n');
  // The template lives one directory below the repo root; the built file
  // lives at the root itself, alongside dev.config.js.
  html = html.replace('src="../dev.config.js"', 'src="dev.config.js"');
  html = html.replace('<script type="module" src="main.js"></script>', '<script>\n' + js + '</script>');

  writeFileSync(OUT, html);
  console.log('Built index.html (' + Math.round(html.length / 1024) + ' KB)');
}

const watchMode = process.argv.includes('--watch');
await build();
if (watchMode) {
  console.log('Watching src/ for changes…');
  watch(SRC, { recursive: true }, () => {
    build().catch((err) => console.error(err));
  });
}
