import html from 'eslint-plugin-html';
import globals from 'globals';

export default [
  // index.html is generated by `node build.js` from src/ — lint the sources
  // it's built from instead (the src/**/*.js block below, and src/index.html
  // via the *.html block, which no longer has anything to lint since its
  // <script> tags are all external now).
  { ignores: ['node_modules', 'playwright-report', 'test-results', 'docs/reference', 'index.html'] },
  {
    files: ['**/*.html'],
    plugins: { html },
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'script',
      globals: { ...globals.browser }
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }]
    }
  },
  {
    files: ['src/**/*.js', 'dev.config.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'module',
      globals: { ...globals.browser }
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }]
    }
  },
  {
    files: ['tests/**/*.js', 'playwright.config.js'],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'module',
      globals: { ...globals.node }
    }
  },
  {
    files: ['build.js'],
    languageOptions: {
      ecmaVersion: 2022, // top-level await
      sourceType: 'module',
      globals: { ...globals.node }
    }
  }
];
